config/routes.rb
Rails.application.routes.draw do
  resources :constantes
  resources :users
  resources :produits
  
  resources :commandes do
    member do
      post "etat" # changer l'etat d'une commande
    end
  end
  
  get 'login', to: 'sessions#create', as: :create_login
  get 'signout', to: 'sessions#destroy', as: 'signout'
  
  get "public/", to: "public#home", as: "public/"
  get "public/home", to: "public#home", as: "public/home"
  get "public/login_fr" => 'public#login_fr'
  get "public/login_en" => 'public#login_en'
  match "public/login"    => 'public#login', via: [:get, :post]
  get "public/logout"   => 'public#logout'
  get "public/aide"     => 'public#aide'
  get "public/payer"     => 'public#payer'
  match "public/:id/recu" => 'public#recu', via: [:get, :post]
  get "public/:id/recupaiement" => 'public#recupaiement'
  get "public/courriels_bloques" => 'public#courriels_bloques'
  resources :public

  get "paniers/:id/show", to: 'paniers#show', as: 'paniers/show'
  post "paniers/:id/plus", to: 'paniers#add_item', as: 'paniers/plus'
  post "paniers/:id/checkout", to: 'paniers#checkout', as: 'paniers/checkout'
  post "paniers/:id/acheter", to: 'paniers#acheter', as: 'paniers/acheter'
  post "paniers/:id/annuler", to: 'paniers#cancel', as: 'paniers/cancel'
  
  resources :activites do
    member do
      get "listeMembreNatation"
    end
    collection do
      post "listeMembre"
      get "sommaire"
    end
  end
  
  resources :participations do
    collection do
      post "listeMembre"
    end
  end
        
  resources :familles do
    resource :cotisation do
      get 'calcul'             # Calcul de la cotisation
    end
    resources :membres, :paiements, :notes
    member do
      get 'recu'               # Rapport d'impot pour une seule famille
      post 'desactive'           # Mettre inactive la famille
      post 'ecussonsRemis'     # enregistrer que les ecussons sont remis
    end
    collection do
      post 'courriel'          # Expédier un courriel
      get 'courriel'           # Formulaire pour un courriel aux familles
      get 'stats'              # Statistiques du nombre de familles, etc.
      get 'cotisations'        # Rapport des cotisations pour toutes les familles
      get 'pas_courriels'      # Rapport des familles sans adresses courriel
      get 'inactifs'           # Rapport des familles inactives
      get 'ecussons'           # Rapport des ecussons a remettre aux familles
      get 'dues'               # Rapport des cotisation dues
      post 'debutAnnee'        # Remise a zero pour le debut de l'annee
      post 'recus'             # Production des recues pour credit d'impot federal
      post 'exp_recus'         # Envoi des recues pour credit d'impot federal
      post 'annulerRabais'     # Annuler les rabais de pre-inscription
      post 'recherche'         # Recherche d'une famille
    end
  end
        
  get 'rapports' => 'rapports#index'
  get 'operations' => 'operations#index'
  post 'paiements/revenus' => 'paiements#revenus'
  post 'paiements/depots' => 'paiements#depots'
  get 'membres/seniors' => 'membres#seniors'
  get 'membres/sommaire' => 'membres#sommaire' # rapport groupé par code postal
  get 'membres' => 'membres#index'
  post 'notes/rapport' => 'notes#rapport'
    
  get '/' => 'root#index'
  root to: 'root#index'
  
  get 'instructions' => 'root#instructions'
end

app/models/participation.rb
# coding: utf-8
class Participation < ApplicationRecord
  
  validates_presence_of :description_fr, :description_en
  
  # Enregistrer qu'une activite a plusieurs membres
  has_and_belongs_to_many :membres, :join_table => 'participations_membres'
  
  def self.nombreActivites
    return Participation.count
  end
  
    # Retourner la liste des activites. Descriptions de chacune
  def self.descriptions
    res = Hash.new
    acts = Participation.order(:description_fr).select('description_fr, id')
    acts.each do | act |
      res[act.description_fr] = act.id
    end
    return res
  end

end

app/controllers/participations_controller.rb
# coding: utf-8
class ParticipationsController < AdminController
  before_action :check_admin, except: :index
  before_action :authenticate, only: :index

  # GET /participations
  # GET /participations.xml
  def index
    @participations = Participation.order(:description_fr)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @participations }
    end
  end

  # GET /participations/1
  # GET /participations/1.xml
  def show
    @participation = Participation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @participation }
    end
  end

  # GET /participations/new
  # GET /participations/new.xml
  def new
    @participation = Participation.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @participation }
    end
  end

  # GET /participations/1/edit
  def edit
    @participation = Participation.find(params[:id])
  end

  # POST /participations
  # POST /participations.xml
  def create
    if (params[:cancel])
      redirect_to(participations_url)
      return;
    end
    
    @participation = Participation.new(participation_params(params))

    respond_to do |format|
      if @participation.save
        flash[:notice] = 'Participation was successfully created.'
        format.html { redirect_to(@participation) }
        format.xml  { render :xml => @participation, :status => :created, :location => @participation }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @participation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /participations/1
  # PUT /participations/1.xml
  def update
    @participation = Participation.find(params[:id])

    if (params[:cancel])
      redirect_to(@participation)
      return;
    end
    
    respond_to do |format|
      if @participation.update(participation_params(params))
        flash[:notice] = 'Activite was successfully updated.'
        format.html { redirect_to(@participation) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @participation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /participations/1
  # DELETE /participations/1.xml
  def destroy
    @participation = Participation.find(params[:id])
    @participation.destroy

    respond_to do |format|
      format.html { redirect_to(participations_url) }
      format.xml  { head :ok }
    end
  end
  
  # Generer une liste des membres pour une participation
  # L'participation est dans le parametre "participation"
  def listeMembre
    id = params[:participation].to_i
    @participation = Participation.find(id)
    @membres = @participation.membres.order('nom, prenom')
  end

  private
  
  def participation_params(params)
    params.require(:participation).permit([:description_fr, :description_en])
  end
end

app/views/participations/_membre_show.html.erb
<tr>
  <td><%= membre_show.nomPrenom %></td>
  <td><%= number_to_phone(membre_show.famille.tel_soir) %></td>
  <td><%= number_to_phone(membre_show.famille.tel_jour) %></td>
  <td><%= membre_show.famille.courriel1 %></td>
</tr>

app/views/participations/_participation.html.erb
<%= form_for(@participation) do |f| %>

<% unless @participation.errors.full_messages.empty? %>
<div class="alert alert-danger">
  <%  @participation.errors.full_messages.each do |msg| %>
  <p>
    <%= msg %>
  </p>
  <% end %>
</div>
<% end %>

<div class="form-group">
  <label>Description (FR)</label>
  <%= f.text_field :description_fr, class: 'form-control' %>
</div>

<div class="form-group">
  <label>Description (EN)</label>
  <%= f.text_field :description_en, class: 'form-control' %>
</div>

<%= f.submit button_name, :class => "btn btn-primary" %>
<%= f.submit( 'Annuler', {name: 'cancel', class: "btn btn-default"}) %>

<% end %>

app/views/participations/_participation_show.html.erb
<tr>
  <td><%=h participation_show.description_fr %></td>
  <td><%= link_to 'Afficher', participation_show %></td>
  <td><%= link_to 'Modifier', edit_participation_path(participation_show) %></td>
  <td><%= link_to 'Enlever', participation_show, data: {confirm: 'Etes vous certain?'}, :method => :delete %></td>
</tr>

app/views/participations/edit.html.erb
<h1>Modifier une activité</h1>

<%= render :partial => @participation, :locals => { :button_name => "Enregistrer"} %>

app/views/participations/index.html.erb
<h1>Liste de la participation</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Code</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
    <%= render :partial => 'participation_show', :collection => @participations %>
  </tbody>
</table>

<br />

<%= button_to 'Créer une activité', new_participation_path, {method: :get, class: "btn btn-primary"} %>

app/views/participations/listeMembre.html.erb
<h1>Membres pour <%= @participation.description_fr %></h1>

<div>
  <table class="table table-condensed">
    <thead>
      <colgroup>
        <col id="nom"/>
        <col id="soir"/>
        <col id="jour"/>
        <col id="email"/>
      </colgroup>
      <tr>
        <th>Membre</th><th>Tel Soir</th><th>Tel Jour</th><th>Courriel</th>
      </tr>
    </thead>
    <tbody>
      <%= render :partial => 'membre_show', :collection => @membres %>
    </tbody>
  </table>
</div>

app/views/participations/new.html.erb
<h1>Créer une activité</h1>

<%= render :partial => @participation, :locals => { :button_name => "Créer"} %>

app/views/participations/show.html.erb
<h1>Données de: <%= @participation.description_fr -%></h1>

<div class="form-group">
  <label>Description (FR):</label>
  <p class="form-control-static">
    <%= h @participation.description_fr %>
  </p>
</div>

<div class="form-group">
  <label>Description (EN):</label>
  <p class="form-control-static">
    <%= h @participation.description_en %>
  </p>
</div>

<%= link_to 'Modifier', edit_participation_path(@participation) %> |
<%= link_to 'Retour', participations_path %>