config/routes.rb
Rails.application.routes.draw do
  resources :constantes
  resources :users
  resources :produits
  
  resources :commandes do
    member do
      post "etat" # changer l'etat d'une commande
    end
  end
  
  get 'login', to: 'sessions#create', as: :create_login
  get 'signout', to: 'sessions#destroy', as: 'signout'
  
  get "public/", to: "public#home", as: "public/"
  get "public/home", to: "public#home", as: "public/home"
  get "public/login_fr" => 'public#login_fr'
  get "public/login_en" => 'public#login_en'
  match "public/login"    => 'public#login', via: [:get, :post]
  get "public/logout"   => 'public#logout'
  get "public/aide"     => 'public#aide'
  get "public/payer"     => 'public#payer'
  match "public/:id/recu" => 'public#recu', via: [:get, :post]
  get "public/:id/recupaiement" => 'public#recupaiement'
  get "public/courriels_bloques" => 'public#courriels_bloques'
  resources :public

  get "paniers/:id/show", to: 'paniers#show', as: 'paniers/show'
  post "paniers/:id/plus", to: 'paniers#add_item', as: 'paniers/plus'
  post "paniers/:id/checkout", to: 'paniers#checkout', as: 'paniers/checkout'
  post "paniers/:id/acheter", to: 'paniers#acheter', as: 'paniers/acheter'
  post "paniers/:id/annuler", to: 'paniers#cancel', as: 'paniers/cancel'
  
  resources :activites do
    member do
      get "listeMembreNatation"
    end
    collection do
      post "listeMembre"
      get "sommaire"
    end
  end
  
  resources :participations do
    collection do
      post "listeMembre"
    end
  end
        
  resources :familles do
    resource :cotisation do
      get 'calcul'             # Calcul de la cotisation
    end
    resources :membres, :paiements, :notes
    member do
      get 'recu'               # Rapport d'impot pour une seule famille
      post 'desactive'           # Mettre inactive la famille
      post 'ecussonsRemis'     # enregistrer que les ecussons sont remis
    end
    collection do
      post 'courriel'          # Expédier un courriel
      get 'courriel'           # Formulaire pour un courriel aux familles
      get 'stats'              # Statistiques du nombre de familles, etc.
      get 'cotisations'        # Rapport des cotisations pour toutes les familles
      get 'pas_courriels'      # Rapport des familles sans adresses courriel
      get 'inactifs'           # Rapport des familles inactives
      get 'ecussons'           # Rapport des ecussons a remettre aux familles
      get 'dues'               # Rapport des cotisation dues
      post 'debutAnnee'        # Remise a zero pour le debut de l'annee
      post 'recus'             # Production des recues pour credit d'impot federal
      post 'exp_recus'         # Envoi des recues pour credit d'impot federal
      post 'annulerRabais'     # Annuler les rabais de pre-inscription
      post 'recherche'         # Recherche d'une famille
    end
  end
        
  get 'rapports' => 'rapports#index'
  get 'operations' => 'operations#index'
  post 'paiements/revenus' => 'paiements#revenus'
  post 'paiements/depots' => 'paiements#depots'
  get 'membres/seniors' => 'membres#seniors'
  get 'membres/sommaire' => 'membres#sommaire' # rapport groupé par code postal
  get 'membres' => 'membres#index'
  post 'notes/rapport' => 'notes#rapport'
    
  get '/' => 'root#index'
  root to: 'root#index'
  
  get 'instructions' => 'root#instructions'
end

app/models/activite.rb
# coding: utf-8
class Activite < ApplicationRecord
  
  validates_numericality_of :cout, :cout2
  validates_uniqueness_of :code
  validates_presence_of :code, :description_fr
  
  # Enregistrer qu'une activite a plusieurs membres
  has_and_belongs_to_many :membres
  
  #
  # Constantes
  #
  CoursDeNatation = ["Parent et enfant 1", "Parent et enfant 2", "Parent et enfant 3", "Préscolaire 1", "Préscolaire 2", "Préscolaire 3", "Préscolaire 4", "Préscolaire 5", "Nageur 1", "Nageur 2", "Nageur 3","Nageur 4","Nageur 5","Nageur 6","Jeune Sauveteur Initié", "Jeune Sauveteur Averti","Jeune Sauveteur Expert"]
  SessionCoursDeNatation = ["matin en semaine", "soir en semaine"]
  
  # Ces codes doivent etre dans la base de donnees.
  CodeCoursDeNatation = Constantes.instance.codeLeconNatation;
  CodeMedailleDeBronze = 'MB';
  CodeCroixDeBronze = 'CB';
  
  # Retourner la liste des activites. Descriptions de chacune
  def self.descriptions
    res = Hash.new
    acts = Activite.order(:description_fr).select('description_fr, id')
    acts.each do | act |
      res[act.description_fr] = act.id
    end
    return res
  end
  
  def self.natation
    return Activite.find_by_code(Activite::CodeCoursDeNatation)
  end
  
  def membreNatation(session, niveau)
    return self.membres.order("nom, prenom").
      where("cours_de_natation = :cours and session_de_natation = :session", { :cours => niveau, :session => session})
  end
  
  def self.nombreActivites
    return Activite.count
  end
  
  # Generer un tableau avec l'activite et son nombre de membres
  # @return [[<activite>, <nombre de participants>], ...]
  def self.sommaire
    return Activite.joins(:membres).group(:description_fr).count
  end
end

app/controllers/activites_controller.rb
# coding: utf-8
class ActivitesController < AdminController
  before_action :check_su, :only => :update
  before_action :authenticate, :except => :update
  

  # GET /activites
  # GET /activites.xml
  def index
    @activites = Activite.all().order(:code)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @activites }
    end
  end

  # GET /activites/1
  # GET /activites/1.xml
  def show
    @activite = Activite.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @activite }
    end
  end

  # GET /activites/new
  # GET /activites/new.xml
  def new
    @activite = Activite.new
    # au debut on pouvait avoir un frais d'activite pour une famille. n'existe plus. hidden dans la view.
    @activite.gratuite = true
  end

  # GET /activites/1/edit
  def edit
    @activite = Activite.find(params[:id])
  end

  # POST /activites
  # POST /activites.xml
  def create
    if (params[:cancel])
      redirect_to(activites_url)
      return;
    end
    
    @activite = Activite.new(activite_params(params))
    if @activite.save
      flash[:notice] = 'Activite mise à jour.'
      redirect_to(@activite)
    else
      render :action => "new"
    end
  end

  # PUT /activites/1
  # PUT /activites/1.xml
  def update
    @activite = Activite.find(params[:id])

    if (params[:cancel])
      redirect_to(@activite)
      return;
    end
    
    if @activite.update(activite_params(params))
      flash[:notice] = 'Activite mise à jour.'
      redirect_to(@activite)
    else
      render :action => "edit"
    end
  end

  # DELETE /activites/1
  # DELETE /activites/1.xml
  def destroy
    @activite = Activite.find(params[:id])
    @activite.destroy
    redirect_to(activites_url)
  end
  
  # Generer une liste des membres pour une activite
  # L'activite est dans le parametre "activite"
  def listeMembre
    id = params[:activite].to_i
    @activite = Activite.find(id)
    @membres = @activite.membres.all.order(:nom, :prenom)
  end

  # rapport des groupes de natation
  def listeMembreNatation
    @activite = Activite::natation
  end

  # Generer un rapport du nombre de membres par activite
  def sommaire
    @data = Activite.sommaire
  end
  
  private
  
  def activite_params(params)
    params.require(:activite).permit([:code, :description_fr, :description_en, :url_fr, :url_en, :gratuite, :cout, :cout2])
  end

end

app/views/activites/_activite.html.erb
<div class="row">
  <div class="col-sm-8 col-lg-5">
    <%= form_for(@activite) do |f| %>

    <% unless @activite.errors.full_messages.empty? %>
    <div class="alert alert-danger">
      <%  @activite.errors.full_messages.each do |msg| %>
      <p>
        <%= msg %>
      </p>
      <% end %>
    </div>
    <% end %>

    <div class="form-group">
      <label>Code</label>
      <%= f.text_field :code, class: 'form-control' %>
    </div>

    <div class="form-group">
      <label>Description (FR)</label>
      <%= f.text_field :description_fr, class: 'form-control' %>
    </div>

    <div class="form-group">
      <label>URL Description (FR)</label>
      <%= f.text_field :url_fr, class: 'form-control' %>
    </div>

    <div class="form-group">
      <label>Description (EN)</label>
      <%= f.text_field :description_en, class: 'form-control' %>
    </div>

    <div class="form-group">
      <label>URL Description (EN)</label>
      <%= f.text_field :url_en, class: 'form-control' %>
    </div>

    <div class="form-group hidden">
      <label>Gratuit</label>
      <%= f.select(:gratuite, {'oui' => 1, 'non' => 0}, {selected: (@activite.gratuite ? 1 : 0)}, {class: 'form-control'}) %>
    </div>

    <div class="form-group">
      <label>Coût pour le premier membre</label>
      <%= f.text_field :cout, class: 'form-control' %>
    </div>

    <div class="form-group">
      <label>Coût par membre additionel</label>
      <%= f.text_field :cout2, class: 'form-control' %>
    </div>

    <%= f.submit button_name, :class => "btn btn-primary" %>
    <%= f.submit( 'Annuler', {name: 'cancel', class: "btn btn-default"}) %>
    <% end %>

  </div>
</div>

app/views/activites/_activite_show.html.erb
<tr>
  <td><%=h activite_show.code %></td>
  <td><%=h activite_show.description_fr %></td>
  <td><%= link_to 'Afficher', activite_show %></td>
  <td><%= link_to 'Modifier', edit_activite_path(activite_show) %></td>
  <td><%= link_to 'Enlever', activite_show, data: {confirm: 'Etes vous certain?'}, :method => :delete %></td>
</tr>

app/views/activites/_membre_show.html.erb
<tr>
  <td><%= membre_show.nomPrenom %></td>
  <td><%= number_to_phone(membre_show.famille.tel_soir) %></td>
  <td><%= number_to_phone(membre_show.famille.tel_jour) %></td>
  <td><%= membre_show.famille.courriel1 %></td>
  <td><%= membre_show.naissance %></td>
</tr>

app/views/activites/edit.html.erb
<h1>Modifier une activité</h1>
<%= render :partial => @activite, :locals => { :button_name => "Enregistrer"} %>

app/views/activites/index.html.erb
<h1>Listes des activités</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Code</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
    <%= render :partial => 'activite_show', :collection => @activites %>
  </tbody>
</table>

<br />

<%= button_to 'Créer une activité', new_activite_path, {method: :get, class: 'btn btn-primary'} %>

app/views/activites/listeMembre.html.erb
<h1>Membres pour <%= @activite.description_fr %></h1>

<div>
<table class="table table-condensed">
  <thead>
    <tr><th>Membre</th><th>Tel Soir</th><th>Tel Jour</th><th>Courriel</th><th>Naissance</th></tr>
  </thead>
  <tbody>
    <%= render :partial => 'membre_show', :collection => @membres %>
  </tbody>
</table>
</div>

app/views/activites/listeMembreNatation.html.erb
<h1>Membres pour <%= @activite.description_fr %></h1>

<% Activite::SessionCoursDeNatation.each do | session | %>
<% Activite::CoursDeNatation.each do | niveau | %>
<% membres = @activite.membreNatation(session, niveau) %>
<% if !membres.empty? %>
<h2>Session: <%= session %>, Niveau: <%= niveau %></h2>
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Membre</th><th>Tel Soir</th><th>Tel Jour</th><th>Courriel</th><th>Naissance</th>
    </tr>
  </thead>
  <tbody>
    <%= render :partial => 'membre_show', :collection => membres %>
  </tbody>
</table>
<% end %>
<% end %>
<% end %>

app/views/activites/new.html.erb
<h1>Créer une activité</h1>
<%= render :partial => @activite, :locals => { :button_name => "Créer"} %>

app/views/activites/show.html.erb
<h1>Données de: <%= @activite.description_fr -%></h1>
<div class="row">
  <div class="col-sm-8 col-lg-5">

    <div class="form-group">
      <label>Code</label>
      <p class="form-control-static">
        <%= @activite.code %>
      </p>
    </div>

    <div class="form-group">
      <label>Description (FR)</label>
      <p class="form-control-static">
        <%= @activite.description_fr %>
      </p>
    </div>

    <div class="form-group">
      <label>URL Description (FR)</label>
      <p class="form-control-static">
        <%= @activite.url_fr %>
      </p>
    </div>

    <div class="form-group">
      <label>Description (EN)</label>
      <p class="form-control-static">
        <%= @activite.description_en %>
      </p>
    </div>

    <div class="form-group">
      <label>URL Description (EN)</label>
      <p class="form-control-static">
        <%= @activite.url_en %>
      </p>
    </div>

    <div class="form-group hidden">
      <label>Gratuit</label>
      <p class="form-control-static">
        <%= @activite.gratuite ? 'oui' : 'non' %>
      </p>
    </div>

    <div class="form-group">
      <label>Coût pour le premier membre familial</label>
      <p class="form-control-static">
        <%= @activite.cout %>
      </p>
    </div>

    <div class="form-group">
    <label>Coût par membre additionel</label>
    <p class="form-control-static">
      <%= @activite.cout2 %>
    </p>
  </div>
  </div>
</div>

<%= link_to 'Modifier', edit_activite_path(@activite) %> |
<%= link_to 'Retour', activites_path %></div>

app/views/activites/sommaire.html.erb
<h1>Nombre de membres par activité</h1>

<%
=begin
%>
input: @data: Data sous forme d'array d'array tel que decrit dans activite.rb#sommaire
<%
=end
%>

<table class="table">
  <thead>
    <tr>
      <th>Activité</th><th>Nombre de Membres</th>
    </tr>
  </thead>
  <tbody>
    <% @data.each do | act | %>
    <tr>
      <td><%= act[0] %></td><td><%= act[1] %></td>
    </tr>
    <% end %>
  </tbody>
</table>