config/routes.rb
Rails.application.routes.draw do
  resources :constantes
  resources :users
  resources :produits
  
  resources :commandes do
    member do
      post "etat" # changer l'etat d'une commande
    end
  end
  
  get 'login', to: 'sessions#create', as: :create_login
  get 'signout', to: 'sessions#destroy', as: 'signout'
  
  get "public/", to: "public#home", as: "public/"
  get "public/home", to: "public#home", as: "public/home"
  get "public/login_fr" => 'public#login_fr'
  get "public/login_en" => 'public#login_en'
  match "public/login"    => 'public#login', via: [:get, :post]
  get "public/logout"   => 'public#logout'
  get "public/aide"     => 'public#aide'
  get "public/payer"     => 'public#payer'
  match "public/:id/recu" => 'public#recu', via: [:get, :post]
  get "public/:id/recupaiement" => 'public#recupaiement'
  get "public/courriels_bloques" => 'public#courriels_bloques'
  resources :public

  get "paniers/:id/show", to: 'paniers#show', as: 'paniers/show'
  post "paniers/:id/plus", to: 'paniers#add_item', as: 'paniers/plus'
  post "paniers/:id/checkout", to: 'paniers#checkout', as: 'paniers/checkout'
  post "paniers/:id/acheter", to: 'paniers#acheter', as: 'paniers/acheter'
  post "paniers/:id/annuler", to: 'paniers#cancel', as: 'paniers/cancel'
  
  resources :activites do
    member do
      get "listeMembreNatation"
    end
    collection do
      post "listeMembre"
      get "sommaire"
    end
  end
  
  resources :participations do
    collection do
      post "listeMembre"
    end
  end
        
  resources :familles do
    resource :cotisation do
      get 'calcul'             # Calcul de la cotisation
    end
    resources :membres, :paiements, :notes
    member do
      get 'recu'               # Rapport d'impot pour une seule famille
      post 'desactive'           # Mettre inactive la famille
      post 'ecussonsRemis'     # enregistrer que les ecussons sont remis
    end
    collection do
      post 'courriel'          # Expédier un courriel
      get 'courriel'           # Formulaire pour un courriel aux familles
      get 'stats'              # Statistiques du nombre de familles, etc.
      get 'cotisations'        # Rapport des cotisations pour toutes les familles
      get 'pas_courriels'      # Rapport des familles sans adresses courriel
      get 'inactifs'           # Rapport des familles inactives
      get 'ecussons'           # Rapport des ecussons a remettre aux familles
      get 'dues'               # Rapport des cotisation dues
      post 'debutAnnee'        # Remise a zero pour le debut de l'annee
      post 'recus'             # Production des recues pour credit d'impot federal
      post 'exp_recus'         # Envoi des recues pour credit d'impot federal
      post 'annulerRabais'     # Annuler les rabais de pre-inscription
      post 'recherche'         # Recherche d'une famille
    end
  end
        
  get 'rapports' => 'rapports#index'
  get 'operations' => 'operations#index'
  post 'paiements/revenus' => 'paiements#revenus'
  post 'paiements/depots' => 'paiements#depots'
  get 'membres/seniors' => 'membres#seniors'
  get 'membres/sommaire' => 'membres#sommaire' # rapport groupé par code postal
  get 'membres' => 'membres#index'
  post 'notes/rapport' => 'notes#rapport'
    
  get '/' => 'root#index'
  root to: 'root#index'
  
  get 'instructions' => 'root#instructions'
end

app/controllers/rapports_controller.rb
# coding: utf-8
# Classe pour preparer une demande de rapports
#
class RapportsController < AdminController

  before_action :authenticate
  
  # La seule methode est "index". Elle affiche des "forms" qui
  # genere un URL pour le bon controller.
  def index
  end

end

app/views/rapports/index.html.erb
<h1>Rapports</h1>

<h4>Activités</h4>

<h5>Sommaire</h5>
<%= link_to "Sommaires des activités", :controller => 'activites', :action => 'sommaire' %><br/>
<div style="margin-bottom:20px"></div>

<h5>Cours de Natation</h5>
<%= link_to "Groupes de cours de natations", :id => Activite::natation.id, :controller => 'activites', :action => 'listeMembreNatation' %>
<div style="margin-bottom:20px"></div>

<h5>Une Activité</h5>
<%= form_tag( {:controller => 'activites', :action => 'listeMembre'},  {class: "form-horizontal"}) do %>
  <div class="form-group">
      <label class="control-label col-xs-1">Activité:</label>
      <div class="col-xs-2">
        <%= select_tag(:activite, options_for_select(Activite.descriptions), {class: 'form-control'}) %>
      </div>
  </div>
  <%= submit_tag "Générer", :class => "btn btn-default" %>
<% end %>

<hr/>

<h4>Participation communautaire</h4>
<%= form_tag( {:controller => 'participations', :action => 'listeMembre'},  {class: "form-horizontal"}) do %>
  <div class="form-group">
        <label class="control-label col-xs-1">Activité:</label>
        <div class="col-xs-2">
         <%= select_tag(:participation, options_for_select(Participation.descriptions), {class: 'form-control'}) %>
        </div>
  </div>
  <%= submit_tag "Générer", :class => "btn btn-default" %>
<% end %>
<hr/>


<h4>Membres</h4>
<%= link_to "Statistiques", stats_familles_path  %><br/>
Cotisations: 
<%= link_to "HTML",  cotisations_familles_path %> /
<%= link_to "XML", url_options = {controller: 'familles', action: 'cotisations', params: { fmt: :xml}} %> /
<%= link_to "JSON", url_options = {controller: 'familles', action: 'cotisations', params: { fmt: :json}} %>
<br/>
<%= link_to "Ecussons et billets",  ecussons_familles_path %><br/>
<%= link_to "Liste des membres séniors", :controller => 'membres', :action => 'seniors' %><br/>
<%= link_to "Liste des familles sans courriels", :controller => 'familles', :action => 'pas_courriels' %><br/>
<%= link_to "Liste des familles inactives", :controller => 'familles', :action => 'inactifs' %><br/>
<%= link_to "Liste des membres", :controller => 'membres', :action => 'index' %><br/>
<%= link_to "Liste des membres par code postal", :controller => 'membres', :action => 'sommaire' %><br/>
<hr/>

<h4>Revenus</h4>
<%= form_tag({:controller => 'paiements', :action => 'revenus'}, {class: "form-horizontal"}) do %>
  <div class="form-group">
    <label class="control-label col-sm-1">Début</label>
    <div class="col-sm-3 col-lg-2">
     <%= text_field_tag('debut', Date.today, {type: 'date', class: "form-control"}) %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-1">Fin</label>
    <div class="col-sm-3 col-lg-2">
      <%= text_field_tag('fin', Date.today, {type: 'date', class: "form-control"})  %>
     </div>
  </div>
  <%= submit_tag "HTML", :class => "btn btn-default"  %>
  <%= submit_tag "XML", {name: 'xml', :class => "btn btn-default"}  %>
  <%= submit_tag "JSON", {name: 'json', :class => "btn btn-default"}  %>
<% end %>
<hr/>

<h4>Dépôts bancaires</h4>
<%= form_tag({:controller => 'paiements', :action => 'depots'}, {class: "form-horizontal"}) do %>
  <div class="form-group">
    <label class="control-label col-sm-1">Début</label>
    <div class="col-sm-3 col-lg-2">
     <%= text_field_tag('debut', Date.today, {type: 'date', class: "form-control"}) %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-1">Fin</label>
    <div class="col-sm-3 col-lg-2">
      <%= text_field_tag('fin', Date.today, {type: 'date', class: "form-control"})  %>
     </div>
  </div>
  <%= submit_tag "Générer", :class => "btn btn-default"  %>
<% end %>
<p/>
<hr/>

<h4>Notes des familles</h4>
<%= form_tag({:controller => 'notes', :action => 'rapport'}, {class: "form-horizontal"}) do %>
  <div class="form-group">
    <label class="control-label col-sm-1">Début</label>
    <div class="col-sm-3 col-lg-2">
     <%= text_field_tag('debut', Date.today, {type: 'date', class: "form-control"}) %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-1">Fin</label>
    <div class="col-sm-3 col-lg-2">
      <%= text_field_tag('fin', Date.today, {type: 'date', class: "form-control"})  %>
     </div>
  </div>
  <%= submit_tag "Générer", :class => "btn btn-default"  %>
<% end %>
<p/>
<hr/>

<h4>Cotisations dûes</h4>
<p>
<%= link_to "Générer rapport", {:action => "dues", :controller => 'familles'} %>
</p>
<p/>
<hr/>

<h4>Commandes de Produits</h4>
<%= form_tag({:controller => 'commandes', :action => 'index'}, {method: :get, class: "form-horizontal"}) do %>
  <div class="form-group">
    <label class="control-label col-sm-1">Début</label>
    <div class="col-sm-3 col-lg-2">
     <%= text_field_tag('debut', Date.today, {type: 'date', class: "form-control"}) %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-1">Fin</label>
    <div class="col-sm-3 col-lg-2">
      <%= text_field_tag('fin', Date.today, {type: 'date', class: "form-control"})  %>
     </div>
  </div>
  <%= submit_tag("Générer", :class => "btn btn-default")  %>
<% end %>
<p/>
<hr/>