config/routes.rb
Rails.application.routes.draw do
  resources :constantes
  resources :users
  resources :produits
  
  resources :commandes do
    member do
      post "etat" # changer l'etat d'une commande
    end
  end
  
  get 'login', to: 'sessions#create', as: :create_login
  get 'signout', to: 'sessions#destroy', as: 'signout'
  
  get "public/", to: "public#home", as: "public/"
  get "public/home", to: "public#home", as: "public/home"
  get "public/login_fr" => 'public#login_fr'
  get "public/login_en" => 'public#login_en'
  match "public/login"    => 'public#login', via: [:get, :post]
  get "public/logout"   => 'public#logout'
  get "public/aide"     => 'public#aide'
  get "public/payer"     => 'public#payer'
  match "public/:id/recu" => 'public#recu', via: [:get, :post]
  get "public/:id/recupaiement" => 'public#recupaiement'
  get "public/courriels_bloques" => 'public#courriels_bloques'
  resources :public

  get "paniers/:id/show", to: 'paniers#show', as: 'paniers/show'
  post "paniers/:id/plus", to: 'paniers#add_item', as: 'paniers/plus'
  post "paniers/:id/checkout", to: 'paniers#checkout', as: 'paniers/checkout'
  post "paniers/:id/acheter", to: 'paniers#acheter', as: 'paniers/acheter'
  post "paniers/:id/annuler", to: 'paniers#cancel', as: 'paniers/cancel'
  
  resources :activites do
    member do
      get "listeMembreNatation"
    end
    collection do
      post "listeMembre"
      get "sommaire"
    end
  end
  
  resources :participations do
    collection do
      post "listeMembre"
    end
  end
        
  resources :familles do
    resource :cotisation do
      get 'calcul'             # Calcul de la cotisation
    end
    resources :membres, :paiements, :notes
    member do
      get 'recu'               # Rapport d'impot pour une seule famille
      post 'desactive'           # Mettre inactive la famille
      post 'ecussonsRemis'     # enregistrer que les ecussons sont remis
    end
    collection do
      post 'courriel'          # Expédier un courriel
      get 'courriel'           # Formulaire pour un courriel aux familles
      get 'stats'              # Statistiques du nombre de familles, etc.
      get 'cotisations'        # Rapport des cotisations pour toutes les familles
      get 'pas_courriels'      # Rapport des familles sans adresses courriel
      get 'inactifs'           # Rapport des familles inactives
      get 'ecussons'           # Rapport des ecussons a remettre aux familles
      get 'dues'               # Rapport des cotisation dues
      post 'debutAnnee'        # Remise a zero pour le debut de l'annee
      post 'recus'             # Production des recues pour credit d'impot federal
      post 'exp_recus'         # Envoi des recues pour credit d'impot federal
      post 'annulerRabais'     # Annuler les rabais de pre-inscription
      post 'recherche'         # Recherche d'une famille
    end
  end
        
  get 'rapports' => 'rapports#index'
  get 'operations' => 'operations#index'
  post 'paiements/revenus' => 'paiements#revenus'
  post 'paiements/depots' => 'paiements#depots'
  get 'membres/seniors' => 'membres#seniors'
  get 'membres/sommaire' => 'membres#sommaire' # rapport groupé par code postal
  get 'membres' => 'membres#index'
  post 'notes/rapport' => 'notes#rapport'
    
  get '/' => 'root#index'
  root to: 'root#index'
  
  get 'instructions' => 'root#instructions'
end

app/controllers/operations_controller.rb
# coding: utf-8
# Classe pour preparer une demande de rapports
#
class OperationsController < AdminController

  before_action :authenticate
  
  # La seule methode est "index". Elle affiche des "forms" qui
  # genere un URL pour le bon controller.
  def index
  end

end

app/views/operations/index.html.erb
<h1>Opérations</h1>

<h4>Courriels</h4>
<p>
  Permet l'envoi de courriels à un membre, à un groupe de membres, ou à tous.
</p>

<%= button_to('Expédier courriels', {:action => "courriel", :controller => 'familles'}, {method: :get, class: "btn btn-primary"})  %>
<div style="padding-bottom: 30px"></div>

<h4>Eliminer le rabais de pré-inscription</h4>
<p>
  Cette opération élimine le rabais de pré-inscription pour tous les membres qui se sont abonnés lors
  de la période de pré-inscription mais qui n'ont pas envoyé au moins un paiement. Un courriel est expédié.
  <%= button_to("Re-calcule cotisation", {:action => "annulerRabais", :controller => 'familles'}, {method: :post, class: "btn btn-default"}) %>
</p>
<div style="padding-bottom: 30px"></div>

<h4>Fin d'année</h4>
<p>A la fin de l'année, il faut faire deux opérations importantes:</p>
<ol>
  <li>Expédier les reçus d'impôt pour la condition physique des enfants;</li>
  <li>Remettre les données d'abonnement à zéro.</li>
</ol>

<p>Avant de commencer, on devrait avoir les nouveaux tarifs puisque lorsque certains reçoivent leurs reçus d'imôt, ils en
profitent pour se ré-abonner.</p>

<p>Je suggère la procédure suivante:</p>
<ol>
  <li>Générer les reçus: <%= button_to("Générer reçus", {:action => "recus", :controller => 'familles'}, {method: :post, class: "btn btn-default"}) %></li>
  <li>Attendre une journée. Ceci permet au backup de compléter avec toutes les données de l'année précédente.</li>
  <li>Modifier les constantes pour inscrire les nouveaux tarifs et la nouvelle date pour la fin du rabais de pré-inscription: <%= link_to 'Modifier constantes', edit_constante_path(Constantes.instance) %></li>
  <li>Remettre les données d'abonnement à zéro. Vous devez avoir le privilège de super user (voir la table des usagers) pour effectuer cette opération. Prend quelques minutes.<%= button_to("Remise à zéro", {:action => "debutAnnee", :controller => 'familles'},
  {data: {confirm: "ATTENTION: Ceci efface toutes les données de l'année courante. Etes-vous certain?"}, method: :post, class: "btn btn-danger"}) %></li>
  <li>Expédier les reçus d'impôts: <%= button_to("Expédier reçus", {action: "exp_recus", controller: 'familles'},
{data: {confirm: "ATTENTION: Ceci envoie un courriel à tous. Etes-vous certain?"}, method: :post, class: "btn btn-default"}) %></li>
</ol>